---
- name: Install Mysql package
  apt: name={{ item }} state=present
  with_items:
   - mysql-server
   - python-mysqldb

- name: Create Mysql configuration file
  template: src=my.cnf.j2
            dest=/etc/my.cnf
            backup=yes
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes
